// server.ts
import express from 'express';
import cors from 'cors';
import multer from 'multer';
import dotenv from 'dotenv';
import { runPrdPipeline } from "./src/lib/pipeline/prdPipeline.js";
import { createRepo, pushFiles } from './src/lib/integrations/github.js';
import { syncSprint } from './src/lib/integrations/clickup.js';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

const upload = multer({ storage: multer.memoryStorage() });

// --- IN-MEMORY DATABASE (Keeps Frontend Syncing Alive) ---
let dbTasks: any[] = [];
let dbArchitecture: any = { nodes: [], edges: [] };

// ==========================================
// API ROUTES 
// ==========================================

// 1. Analyze PRD Upload
app.post('/api/prd/upload', upload.single('prd'), async (req, res): Promise<any> => {
  try {
    if (!req.file) return res.status(400).json({ error: 'No PDF uploaded.' });

    const documentPart = {
      inlineData: {
        data: req.file.buffer.toString("base64"),
        mimeType: req.file.mimetype,
      },
    };

    // Run the modular Gemini 3.1 Pro pipeline
    const pipelineResult = await runPrdPipeline(documentPart);

    // Sync pipeline results to our in-memory DB for the frontend Sprints board
    // FIXED: Added (t: any) and (s: any) to satisfy TypeScript, plus optional chaining
   dbTasks = pipelineResult.tasks.map((t: any) => ({
      ...t,
      status: 'todo',
      story: pipelineResult.stories?.find((s: any) => s.id === t.storyId)?.story || "Core Task",
      type: 'Feature',
      priority: 'High',
      points: t.complexity || 3
    }));
    
    // Sync traceability matrix for frontend Graph
    dbArchitecture = pipelineResult.architecture;

    return res.json({ success: true, data: pipelineResult });
  } catch (error: any) {
    console.error('Pipeline Error:', error);
    return res.status(500).json({ error: error.message });
  }
});

// 2. Fetch Tasks for Sprints Page
app.get('/tasks', (req, res) => res.json(dbTasks));

// 3. Update Task Status (Drag & Drop)
app.patch('/tasks/:id', (req, res) => {
  const taskIndex = dbTasks.findIndex(t => t.id === req.params.id);
  if (taskIndex > -1) {
    dbTasks[taskIndex].status = req.body.status;
    res.json({ success: true, task: dbTasks[taskIndex] });
  } else {
    res.status(404).json({ error: "Task not found" });
  }
});

// 4. Fetch Traceability Graph
app.get('/traceability', (req, res) => res.json(dbArchitecture));

// 5. GitHub Push Integration
app.post('/api/push-to-github', async (req, res): Promise<any> => {
  try {
    const { repoName, files } = req.body;
    
    // 1. Create the repo
    await createRepo(repoName, "Generated by Architecture Assistant");
    
    // 2. Push the code structure
    const pushResult = await pushFiles("owner", repoName, files || []);
    
    return res.json({ success: true, data: pushResult });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

// 6. ClickUp Sync Integration
app.post('/api/sync-clickup', async (req, res): Promise<any> => {
  try {
    const { listId, sprint } = req.body;
    
    if (!listId || !sprint) {
      return res.status(400).json({ error: "Missing listId or sprint data" });
    }

    const result = await syncSprint(listId, sprint);
    return res.json({ success: true, data: result });
  } catch (error: any) {
    return res.status(500).json({ error: error.message });
  }
});

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
  console.log(`🚀 Modular Gemini Backend running on http://localhost:${PORT}`);
});